# src/riser/slip_rates/__init__.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2025 Rob Zinke. Licensed under the MIT License.

"""
Slip rate estimates (represented as PDFs) are the key output generated by
RISeR2.
"""

__all__ = [
    "rate_computation",
    "reporting",
]

from . import rate_computation
from . import reporting


# end of file
