"""
Slip rate estimates (represented as PDFs) are the key output generated by
RISeR2.
"""

__all__ = [
    "rate_computation",
    "reporting",
]

from . import rate_computation
from . import reporting
